collect_data:
  stage: build
  image: registry.cloud.fits/devops-services/toolchain/docker-go:v0.6.0
  timeout: 60m
  variables:
    GIT_SSL_NO_VERIFY: "true"
  script:
    - echo "Displaying OS information"
    - cat /etc/os-release || lsb_release -a || uname -a

    # Update package lists and install dependencies with retry
    - |
      echo "Updating package lists and installing dependencies"
      RETRY=3
      until apt-get update && apt-get install -y curl jq python3 python3-pip git; do
        RETRY=$((RETRY-1))
        if [ $RETRY -le 0 ]; then
          echo "Error installing dependencies after retries"
          exit 1
        fi
        echo "Retrying dependency installation"
        sleep 5
      done

    # Retry logic for kubectl download
    - |
      KUBECTL_RETRIES=3
      KUBECTL_DOWNLOAD_SUCCESS=false
      KUBECTL_VERSION="v1.28.0"
      for ((i=1; i<=KUBECTL_RETRIES; i++)); do
        echo "Download attempt $i of $KUBECTL_RETRIES..."
        if timeout 300 curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"; then
          echo "kubectl download succeeded on attempt $i."
          KUBECTL_DOWNLOAD_SUCCESS=true
          break
        else
          echo "kubectl download failed on attempt $i. Retrying..."
          sleep 10
        fi
      done
      if [ "$KUBECTL_DOWNLOAD_SUCCESS" = false ]; then
        echo "kubectl download failed after $KUBECTL_RETRIES attempts."
        exit 1
      fi

    # Make kubectl executable and move to bin
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/kubectl || { echo "Error moving kubectl to /usr/local/bin"; exit 1; }

    # Verify kubectl installation
    - kubectl version --client || { echo "kubectl installation verification failed"; exit 1; }

    # Install Python dependencies with retry
    - |
      echo "Installing Python dependencies"
      RETRY=3
      until pip3 install --no-cache-dir tabulate; do
        RETRY=$((RETRY-1))
        if [ $RETRY -le 0 ]; then
          echo "Error installing Python dependencies after retries"
          exit 1
        fi
        echo "Retrying Python dependencies installation"
        sleep 5
      done

    # Create kubeconfig files and handle any related errors
    # [Same steps as in the current script, possibly with better error messages and logging for clarity]
