stages:
  - build

build_cluster_info:
  stage: build
  image: registry.cloud.fits/devops-services/toolchain/docker-go:v0.6.0
  variables:
    KUBECONFIG_CONTENT: $KUBECONFIG_CONTENT  # Kubeconfig content stored as a CI variable
  script:
    - apt-get update && apt-get install -y kubectl jq git
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_CONTENT" > ~/.kube/config
    - chmod 600 ~/.kube/config
    - ./your_bash_script.sh
    - if [ -d "info_cache_*" ]; then
        echo "info_cache_* directory exists.";
      else
        echo "Error: info_cache_* directory does not exist.";
        exit 1;
      fi
    - mkdir -p boms/k8s/ingress
    - mkdir -p boms/k8s/pods
    - cp -r info_cache_*/ingress.json boms/k8s/ingress/
    - cp -r info_cache_*/pods.json boms/k8s/pods/
