collect_data:
  stage: build
  image: registry.cloud.fits/fits/appcore-k8s-builder:2.8.1
  timeout: 60m
  variables:
    GIT_SSL_NO_VERIFY: "true"
    no_proxy: github.com,objects.githubusercontent.com  # Disable proxy for GitHub-related domains
  script:
    # Verify if yq is installed
    - yq --version || echo "yq is not installed"

    # Install yq if not present
    - |
      if ! command -v yq &> /dev/null; then
        echo "Installing yq"
        wget -O /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64" \
          && chmod +x /usr/local/bin/yq || { echo "Error installing yq"; exit 1; }
      fi

    # Install Python dependencies
    - echo "Installing Python dependencies"
    - pip3 install --no-cache-dir tabulate || { echo "Error installing Python dependencies"; exit 1; }

    # Create a temporary directory for kubeconfig files
    - echo "Creating directory for kubeconfig files"
    - mkdir -p /tmp/kubeconfigs || { echo "Error creating kubeconfigs directory"; exit 1; }

    # Write kubeconfig variables to files with additional logging
    - echo "Writing kubeconfig variables to files with additional logging"
    - |
      kubeconfig_variables=(
        "fttc_tdf01_kubeconfig" "fttc_tds01_kubeconfig" "fttc_tf01_kubeconfig" "fttc_ts01_kubeconfig"
        "fttc_pdf01_kubeconfig" "fttc_pds01_kubeconfig"
        "ftctl_pf01_kubeconfig" "ftctl_ps01_kubeconfig"
      )

      for var_name in "${kubeconfig_variables[@]}"; do
        cluster_name="${var_name%_kubeconfig}"
        kubeconfig_content="${!var_name}"

        if [ -z "$kubeconfig_content" ]; then
          echo "Error: Kubeconfig variable $var_name is empty or not set"
          exit 1
        fi

        echo "$kubeconfig_content" | base64 --decode > "/tmp/kubeconfigs/${cluster_name}_kubeconfig" || {
          echo "Error writing kubeconfig for $cluster_name"; exit 1;
        }

        # Log the length of the kubeconfig to ensure it has content (but not the content itself)
        config_length=$(wc -c < "/tmp/kubeconfigs/${cluster_name}_kubeconfig")
        if [ "$config_length" -eq 0 ]; then
          echo "Error: Kubeconfig file for $cluster_name is empty after decoding"
          exit 1
        else
          echo "Kubeconfig for $cluster_name successfully written with size ${config_length} bytes"
        fi

        chmod 600 "/tmp/kubeconfigs/${cluster_name}_kubeconfig" || {
          echo "Error setting permissions on kubeconfig for $cluster_name"; exit 1;
        }
      done

    # Ensure scripts are executable
    - echo "Ensuring scripts are executable"
    - chmod +x scripts/cluster_crawler.sh

    # Run the cluster crawler script with additional logging
    - echo "Running cluster crawler script with additional logging"
    - ./scripts/cluster_crawler.sh -dl || {
        echo "Cluster crawler script failed";
        # Output contents of the kubeconfig directory for debugging
        echo "Listing kubeconfig files for debugging:";
        ls -l /tmp/kubeconfigs;
        exit 1;
      }

    # Log available contexts after merging kubeconfig files
    - echo "Logging available contexts after merging kubeconfig files"
    - export KUBECONFIG=$(find /tmp/kubeconfigs -type f -exec printf '{}:' \;)
    - kubectl config view --flatten > /tmp/merged_kubeconfig || { echo "Error flattening kubeconfig"; exit 1; }
    - export KUBECONFIG=/tmp/merged_kubeconfig
    - echo "Available contexts after merging:"; kubectl config get-contexts || { echo "Error getting contexts"; exit 1; }

    # Run additional checks on merged kubeconfig to ensure contexts are present
    - echo "Checking merged kubeconfig for all expected contexts"
    - |
      for cluster_name in "${kubeconfig_variables[@]%%_kubeconfig}"; do
        if ! kubectl config get-contexts | grep -q "$cluster_name"; then
          echo "Warning: Context for $cluster_name not found in merged kubeconfig"
        else
          echo "Context for $cluster_name found"
        fi
      done

    # Clean up temporary files
    - echo "Cleaning up temporary files"
    - rm -rf /tmp/kubeconfigs || { echo "Error cleaning kubeconfigs"; exit 1; }
    - rm -f /tmp/merged_kubeconfig || { echo "Error cleaning merged kubeconfig"; exit 1; }

  artifacts:
    paths:
      - scripts/info_cache_*
    expire_in: 1 week
