collect_data:
  stage: build
  variables:
    GIT_SSL_NO_VERIFY: "true"
  script:
    # Install EPEL repository and necessary dependencies
    - yum install -y epel-release
    - yum update -y && yum install -y curl jq git python3 python3-pip

    # Install kubectl
    - KUBECTL_VERSION="v1.28.0"
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/kubectl
    - kubectl version --client  

    # Install Python dependencies
    - pip3 install --no-cache-dir tabulate

    # Set up Kubernetes config securely
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG_DATA_1" | base64 --decode > ~/.kube/config
    - chmod 600 ~/.kube/config

    # Check the Kubernetes config without exposing sensitive information
    - kubectl config view --minify

    # Ensure scripts are executable
    - chmod +x scripts/cluster_crawler.sh
    - chmod +x scripts/parser.py

    # Run the cluster crawler script
    - ./scripts/cluster_crawler.sh
