image: registry.cloud.fits/devops-services/toolchain/docker-go:v0.6.0

stages:
  - validate
  - build
  - deploy

# Überprüfen des Shell-Skripts
lint:
  stage: validate
  allow_failure: true
  variables:
    SHELLCHECK_OPTS: ""
  script:
    - shellcheck scripts/cluster_crawler.sh

# Schritt 1: Kubernetes-Daten sammeln und deployen
collect_data:
  stage: build
  script:
    # kubectl installieren
    - KUBECTL_VERSION="v1.28.0"
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/kubectl
    - kubectl version --client  

    # jq installieren
    - curl -L -o jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    - chmod +x ./jq
    - mv jq /usr/local/bin/jq
    - jq --version 

    - mkdir -p ~/.kube #.kube Verzeichnis
    - cp "$KUBE_CONFIG_DATA" ~/.kube/config  # Kubernetes-Konfigurationsdatei aus den CI-Variablen laden
    - chmod 600 ~/.kube/config  # Berechtigungen für die Kubernetes-Konfigurationsdatei setzen
    - kubectl config view  # Überprüfen, ob die Kubernetes-Konfigurationsdatei korrekt ist
    - chmod +x scripts/cluster_crawler.sh  # Skript ausführbar machen
    - ./scripts/cluster_crawler.sh  # Datensammelskript ausführen
    - python3/scripts/parser.py #Datenformatierungsskript ausführen

