collect_data:
  stage: build
  image: registry.cloud.fits/devops-services/toolchain/docker-go:v0.6.0
  timeout: 60m
  variables:
    GIT_SSL_NO_VERIFY: "true"
  script:
    # Display OS information
    - echo "Displaying OS information"
    - cat /etc/os-release || lsb_release -a || uname -a

    # Update package lists and install dependencies
    - echo "Updating package lists and installing dependencies"
    - apt-get update && apt-get install -y curl jq python3 python3-pip git wget || { echo "Error installing dependencies"; exit 1; }

    # Install yq (YAML processor)
    - echo "Installing yq"
    - wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64 && chmod +x /usr/local/bin/yq || { echo "Error installing yq"; exit 1; }

    # Install kubectl with retry logic
    - |
      KUBECTL_RETRIES=5
      KUBECTL_DOWNLOAD_SUCCESS=false
      KUBECTL_VERSION="v1.28.0"
      KUBECTL_EXPECTED_SIZE=49836544  # Adjust if necessary

      for ((i=1; i<=KUBECTL_RETRIES; i++)); do
        echo "Download attempt $i of $KUBECTL_RETRIES..."
        if timeout 300 curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"; then
          if [ $(stat -c%s "kubectl") -ge $KUBECTL_EXPECTED_SIZE ]; then
            echo "kubectl download succeeded on attempt $i and verified file size."
            KUBECTL_DOWNLOAD_SUCCESS=true
            break
          else
            echo "kubectl download incomplete (wrong file size), retrying..."
            rm -f kubectl
          fi
        else
          echo "kubectl download failed on attempt $i. Retrying..."
          sleep 10
        fi
      done

      if [ "$KUBECTL_DOWNLOAD_SUCCESS" = false ]; then
        echo "kubectl download failed after $KUBECTL_RETRIES attempts."
        exit 1
      fi

    # Make kubectl executable and move to bin
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/kubectl || { echo "Error moving kubectl to /usr/local/bin"; exit 1; }

    # Verify kubectl installation
    - kubectl version --client || { echo "kubectl installation verification failed"; exit 1; }

    # Install Python dependencies
    - echo "Installing Python dependencies"
    - pip3 install --no-cache-dir tabulate || { echo "Error installing Python dependencies"; exit 1; }

    # Create a temporary directory for kubeconfig files
    - echo "Creating directory for kubeconfig files"
    - mkdir -p /tmp/kubeconfigs || { echo "Error creating kubeconfigs directory"; exit 1; }

    # Write each kubeconfig variable to a file
    - echo "Writing kubeconfig variables to files"
    - |
      # List of kubeconfig variable names
      kubeconfig_variables=("fttc_tdf01_kubeconfig" "fttc_tds01_kubeconfig" "fttc_tf01_kubeconfig" "fttc_ts01_kubeconfig")

      for var_name in "${kubeconfig_variables[@]}"; do
        echo "Processing variable: [MASKED]"
        
        # Access the base64-encoded variable value
        kubeconfig_base64="${!var_name}"

        # Check if the variable is set
        if [ -z "$kubeconfig_base64" ]; then
          echo "Error: Kubeconfig variable $var_name is empty or not set"
          exit 1
        fi

        # Decode the base64 content and write to the kubeconfig file
        cluster_name="${var_name%_kubeconfig}"
        echo "$kubeconfig_base64" | base64 --decode > "/tmp/kubeconfigs/${cluster_name}_kubeconfig" || { echo "Error decoding kubeconfig for $cluster_name"; exit 1; }

        # Secure the kubeconfig file
        chmod 600 "/tmp/kubeconfigs/${cluster_name}_kubeconfig" || { echo "Error setting permissions on kubeconfig for $cluster_name"; exit 1; }
      done

    # Ensure scripts are executable
    - echo "Ensuring scripts are executable"
    - chmod +x scripts/cluster_crawler.sh
    - chmod +x scripts/parser.py

    # Run the cluster crawler script
    - echo "Running cluster crawler script"
    - ./scripts/cluster_crawler.sh -dl || { echo "Cluster crawler script failed"; exit 1; }

    # Clean up temporary files
    - echo "Cleaning up temporary files"
    - rm -rf /tmp/kubeconfigs || { echo "Error cleaning kubeconfigs"; exit 1; }
    - rm -f /tmp/merged_kubeconfig || { echo "Error cleaning merged kubeconfig"; exit 1; }

  artifacts:
    paths:
      - scripts/info_cache_*
    expire_in: 1 week
