---

image: registry.cloud.fits/devops-services/toolchain/docker-go:v0.6.0

stages:
  - validate

lint:
  stage: validate
  allow_failure: true
  variables:
    SHELLCHECK_OPTS: ""
  script:
    - shellcheck scripts/cluster_crawler.sh